### ISSUE TITLE
2.2.3 Functionality to filter displayed movies by genre

### ISSUE THREAD

**Issue by Fagerdahl** [RobTrb/Kino-Scrum#42]
## Type
Features

## Description / User Story
As a user I want to find a filtered list on movies based on a chosen specific genres from a dropdown-bar on the startpage

## Defintion of Done
When chosing a specific genre in the dropdown-bar, movies get filtered and displayed to match the chosen genre. 

## Tasks
- [ ] Add filter functionality with JS to present movies of following genres:
- [ ] Action
Adventure
Science Fiction
Drama
Comedy
Thriller
Horror
Swedish movies
Childens movies
- [ ] Connect filterfunction to drop-down bar with an eventlistener
- [ ] Render the page and display only movies by requested genre

## Dependencies
- #73 
- #40 
- #77
