### ISSUE TITLE
1.1  Header: Title/Navstructure

### ISSUE THREAD

**Issue by Deansie** [RobTrb/Kino-Scrum#44]
## Type:
Styling/Visuals

## Description / User Story:
As a user. I want to...

- see a consistent title/header on every page so I can maintain a sense of the overall site structure regardless to what page 
- have a structure for a menu to help me navigate the website

## Tasks

- [ ] Create a div for the top of the webpage that should be under the title and be ready for button implementation. 
- [ ] The design should follow the before agreed upon design specification (see attachment).

## Defintion of Done:

- [ ] The header is visible at the top of every webpage in the site
- [ ] The header's font and style is consistent to the predetermined design (see attachment)
- [ ] There is a visible bar ready for button implementation

## Dependencies:

- #73 
- #59

## Notes:
 - The card 1.2.1 created by Robert has been merged into this card

![Image](https://github.com/user-attachments/assets/e5c857a4-cfcc-4b79-a6bc-cd6f3544dcf5)

**Comment by Deansie** [comment]
Well done, a good first step before implementing buttons!
