### ISSUE TITLE
1.2.2 Header: Navigation Buttons

### ISSUE THREAD

**Issue by AlexCode-dot** [RobTrb/Kino-Scrum#47]
**Type**
Feature

**Description/User story**
 As a user, I want to easily navigate the website using visible and accessible buttons, so I can quickly find relevant information and sections

**Definition of done**
The header of the website should contain a navigation bar with the following buttons: 

- Filmer
- Barnbio
- Evenemang
- Om oss
- Logga in 

**Tasks**

- [ ] Define the layout, positioning, and spacing of the buttons, ensuring they are visually appealing and easy to interact with.
- [ ] Ensure that the buttons are easily distinguishable, accessible, and provide proper feedback when hovered or clicked.
- [ ]  The navigation buttons is functional and visually appropriate across multiple devices.
- [ ] Add functionality to get to startpage when pressing "Filmer"

<img width="1074" alt="Image" src="https://github.com/user-attachments/assets/ecf12b30-8cfb-40d7-b825-2a3bbb940214" />

**Dependencies**
- #44 
- #73
