### ISSUE TITLE
4.5 Footer: Style

### ISSUE THREAD

**Issue by Deansie** [RobTrb/Kino-Scrum#49]
## Type:
Styling

## Description / User Story:
As a user, I want to see a consistent and informative footer at the bottom of each webpage so that I can easily access relevant information about the cinema such as contact information and important links.

## Tasks

- [ ] Tweak div-structure to fit the content properly 
- [ ] Style the footer according to predetermined design specifications
- [ ] Add links to following content:

        - Email adresses (mail:to)
        - Phone numbers (tel:)

## Definition of Done:

- [ ] The footer is visible at the bottom of every webpage in the site
- [ ] The footer's font and style is consistent to the predetermined design (see attachment)
- [ ] All links in the footer are functional and leads to the correct destination
- [ ] All content is grammatically correct

## Dependencies:
- #56 
- #58 
- #57 
- #59 

![Image](https://github.com/user-attachments/assets/8d27c6ab-0079-4c3c-9506-3da2500fd789)
