### ISSUE TITLE
1.2.4 Navigation animation

### ISSUE THREAD

**Issue by Patseroni** [RobTrb/Kino-Scrum#51]
**Type:**
Feature

**User story:**
As a user, I want to see a nice, subtle animation of the navigation bar when I enter the pages.

**Description:**
The animation can be shown on all the pages that the user enters, so it’s important that the animation is subtle and not distracting for the user, just a slightly more visually appealing experience. Choose what type of animation you want.

**Defintition of done:**
A subtle, simple animation of the whole navigation-bar when the pages are loading.

## Tasks
- [ ] Highlight the current menu
- [ ] Animate the already existing mobile menu, display it. Toggle mobile menu in this step.
- [ ] Add HOVER in desktop menu

**Dependencies:**
- #44 
- #47 
- #43
