### ISSUE TITLE
5.3 Kids: Show only moviecards suitable for <12 years

### ISSUE THREAD

**Issue by RobTrb** [RobTrb/Kino-Scrum#52]
**Type**

Feature

**Description / User Story**
As a user i would like to be able to klick on “barnbio” and have the site present movies that are suitable for children under the age of 12

**Tasks**

- [x] Add click event to menu button called “barnbio”
- [x] Create a function that filters and only shows movies that are suitable for ages under 12
- [x] Make the click event call that function and display the sorted result 

**Styling**

Has the same styling of the cards already done in one of the dependencies

**Definition of done**

When you can click the “barnbio” button and get the expected result mentioned above

**Dependencies**

- #63 
- #40 
- #70
