### ISSUE TITLE
2.1.1 Develop search logic

### ISSUE THREAD

**Issue by RobTrb** [RobTrb/Kino-Scrum#55]
**Type**

Technical

**Description / User Story**
As a user I would like to be able to searh on the site to find movies

**Tasks**

Code the functionality behind the search bar. The function needs to be able to:

- [x] Read the data which the user types in the search field
- [x] Use the data to filter the list of movies to only have the movies that fit the search querry
- [x] Return filtered result

**Definition of done**
When it can take the data from the unput field, filter the list and return a result.

Styling

None

**Dependencies**

- #63 
- #40
