### ISSUE TITLE
4.2 Footer: Add contact information

### ISSUE THREAD

**Issue by Deansie** [RobTrb/Kino-Scrum#56]
## Type:
Feature

## Description / User Story:
As a user, I want to see contact information in the footer at the bottom of each webpage so that I can easily access information on how to come in contact with the cinema in various ways.

## Tasks

- [ ] Add contact information as per predetermined design
- [ ] Add contact details for:
     
    - Company name
    - Physical adress
    - Phone numbers
    - Email adresses

## Definition of Done:

- [ ] Contact information is visible in the footer at the bottom of every webpage in the site
- [ ] The following contact details are included:

      - Company name
      - Physical adress
      - Phone numbers
      - Email adresses

- [ ] All contact information are up-to-date and accurate

## Dependencies:

- #49 
- #59 

![Image](https://github.com/user-attachments/assets/776c0bab-3c33-42cb-915c-ae743fd4de14)
