### ISSUE TITLE
7. Frontpage: Design

### ISSUE THREAD

**Issue by Deansie** [RobTrb/Kino-Scrum#59]
Type:
Style

Description / User Story:
As a developer, I want to implement the approved Figma design for the frontpage, ensuring that the live webpage accurately reflects the design specifications and functions correctly in desktop-view.

Defintion of Done:

- [x] The frontpage HTML, CSS and JavaScript accurately reflect the approved Figma design
- [x] All sections of the frontpage (header, main content area, footer) are implemented as per the design
- [x] All colors match the Figma specifications
 
        - Colors: #03658C , #012840

- [x] All images have appropriate alt text and are optimized for web

Dependencies:

- #76 
- #77 
- #78 
- #79 

![Image](https://github.com/user-attachments/assets/54f11756-5c2a-4d94-a88d-3c41a3417e88)
