### ISSUE TITLE
3.1.1 Create fake movie API data in json format

### ISSUE THREAD

**Issue by RobTrb** [RobTrb/Kino-Scrum#63]
**Type**

Technical

**Description / User Story**

As a user I want a list of movies to choose from

**Tasks**

Create a json file concisting of movie data. Relevant data for the movies should be:

- [ ] - ID (unique id for each movie)
- [ ] - Title (the title of the movie)
- [ ] - Description (plot summary)
- [ ] - Runtime (length of the movie in hours and minutes)
- [ ] - Rating (rating of the movie that goes from 0 to 5)
- [ ] - Age (appropriate age for the movie, data can be found on IMDB for each movie)
- [ ] - start date
- [ ] - end date
- [ ] -actors
- [ ] - genre
- [ ] - image poster

<img width="740" alt="Image" src="https://github.com/user-attachments/assets/15ab4165-3eba-4b15-8745-1b85686ba3f7" />

**Definition of done**
When there is a finished json file that can be used for the prototype webpage that consists of at least 30 movies.

**Styling**
No styling required

**Dependencies**
None

**Comment by Fagerdahl** [comment]
https://kino.internetbokningen.com/chap/ajax/getAllMovies
lägger den här
