### ISSUE TITLE
5.1.1 Replace background to match childrens movies

### ISSUE THREAD

**Issue by Kalu32k** [RobTrb/Kino-Scrum#64]
## Type
Feature

## Description / User Story
As a user I would like the website to change the background to a more kid friendly theme when i click the "Barnbio" section so that it reflects a fun and kid friendly theme.

## Tasks

- [x] Add a click event listener to the menu button called "Barnbio".
- [x] Create a function that changed the websites background to a kid friendly theme.
- [x] Make sure the theme stay while viewing the movie section for kids and go back to the original theme when navigating away.

## Styling
Use cheerful colors and/or balloons, clouds, stars.

## Definition of done
Clicking the "Barnbio" button changes the background to a kid friendly theme.
The background reverts back to the original theme when navigating away from the kid section.
The change is responsive and works consistent on multiple devices.

## Dependencies
- #47
