### ISSUE TITLE
3.3.1 Function to create a modal with movie title when clicking on a moviecard

### ISSUE THREAD

**Issue by Kalu32k** [RobTrb/Kino-Scrum#66]
## Type
Feature

## Description / User Story
As a user I want to see a modal with the movie title when I click on a movie card so I can easily see more information about the selected movie.
## Tasks

- [x] Create a function that opens a modal when a movie card is clicked.
- [x] Pass the movie information to the modal.
- [x] Add a close button and/or click outside the area to close the modal function.
- [x] Create a function that removes the element when closing the modal.

## Styling
![Image](https://github.com/user-attachments/assets/238e64cd-21ca-4d47-8e1c-4fa85b1e6b27)

- #60 
## Definition of done

- Clicking a movie card opens a modal displaying the movie information.
- The modal can be closed with a button or clicking outside the modal.
- Modal is responsive and works on multiple devices.

## Dependencies
- #70 
- #67
