### ISSUE TITLE
3.3.3 Function to display movie information from specific movie from API data

### ISSUE THREAD

**Issue by Kalu32k** [RobTrb/Kino-Scrum#67]
## Type
Feature

## Description / User Story
As a developer I want to create a function to fetch information of a specific movie from the API so the website can display it when users select a specific movie.
## Tasks

- [ ] Write a function to fetch movie details from the API using identifier such as movie title or ID.
- [ ] Parse and extract API response data to relevant details such as (Title, ID, Genre, Length, Description, Picture).
- [ ] Handle error if fetch from API fail.

## Styling
![Image](https://github.com/user-attachments/assets/b5758e77-b1a6-4ba7-a99b-1bd0e98d59e8)

## Definition of done

- The function fetches and desplays movie details when a movie card is selected.
- Error handling provides clear feedback if missing data.

## Dependencies
- #63
