### ISSUE TITLE
4.1 Footer: Add social media links

### ISSUE THREAD

**Issue by Hungryhippoafk** [RobTrb/Kino-Scrum#68]
### User Stories
As a user, I want to see clearly displayed social media icons in the footer so I can easily find and access the cinema's official social media pages.

### BDD
Given: User is using the footer.
When: user is checking links for websites socials.
Then: User shall experience smooth , appealing and responsive links.

###  Task

- [ ] Select and add visually appealing social media icons(Facebook, instagram,Twitter).
- [ ] Add responsive social media icons
- [ ] Social media icons are positioned after figma design.

### **Design and styling**
![Image](https://github.com/user-attachments/assets/bfa9bd51-0e32-4088-8b1e-3e179e69f5f0)

### Acceptance Criteria/Definition of Done

- Social media icons are displayed prominently in the footer.
- Each icon links to the respective social media page (e.g., Facebook, Instagram, Twitter).
- Icons are responsive and optimized for mobile,  desktop views.

### Dependencies
- #49
