### ISSUE TITLE
8. Setup json files that will contain frontpage content and functionality to fetch the content

### ISSUE THREAD

**Issue by AlexCode-dot** [RobTrb/Kino-Scrum#73]
**Type**
Technical

**Description / User Story**
As a developer,
I want to set up JSON files that contain the front-page content and implement functionality to fetch and that content,
so that the front page can dynamically load and present content from a maintainable source

**Tasks**

- [ ] Create two json files. One for frontpage text content and one for images content
- [ ] Create the structure for the JSON files that will hold the front-page content like (sections for header, body, footer etc)
- [ ] Create a function that is able to fetch the json content asynchronously, so content can be added dynamically to the DOM when needed
- [ ] Create a try/catch error handling, and display error message. 
- [ ] Load the content according the design (Not movie cards): https://www.figma.com/design/AuEExXRa2UHa2wlXG4TPcu/Kvikkjokk-Kino?node-id=0-1&p=f&t=2GqIxdfNE7TL0cOF-0

**Defintion of Done**

- A well-defined JSON schema is created for storing front-page content like "title", "navigation", "images" etc
- A function that is able to fetch the json content asynchronously, so content can be added dynamically to the DOM when needed
- The functionality should properly handle errors (e.g., no content, server issues) and display fallback content if necessary

**Dependencies**
- ...
