### ISSUE TITLE
3.2.2 Style moviecards in sass

### ISSUE THREAD

**Issue by Kalu32k** [RobTrb/Kino-Scrum#74]
## Type
Styling

## Description / User Story
As a developer I want to style movie cards with SASS so they are visually appealing and matches with the website design.
## Tasks

- [ ] Create a SASS file from movie card styling.
- [ ] Style the card, more on that in the styling section.
- [ ] Import the movie card styles into main SASS file and compile CSS.

## Styling
Desktop layout:
![Image](https://github.com/user-attachments/assets/b31e0698-9ce9-458e-90c1-ef5a212d3a23)
Mobile layout:
![Image](https://github.com/user-attachments/assets/f3dc4232-46a4-4fdd-9a1e-04aae9ad68b4)
Style template:
![Image](https://github.com/user-attachments/assets/2a9ccf8a-c3ab-4a20-a67d-866f6e9c1437)

- The cards should have a hover effect on them that adds drop shadow.
- The cards should match the website color design.
- Mobile version should be smaller to fit the screen better.

## Definition of done

- Movie cards are fully styled and matches with the website design.
- Cards are responsive and works on multiple devices.
- Hover effect is implemented to enhance the user experience.

## Dependencies
- #70 
- #40 
- #63
